### ISSUE TITLE
'content-length' missing

### ISSUE THREAD

**Issue by bionanopatterning** [chanzuckerberg/cryoet-data-portal#1132]
Hi,

I was using the cryoet-data-portal module in Python to download some tomograms from dataset 10302 when I encountered this issue:

```
id = 10302

client = Client()
dataset = Dataset.get_by_id(client, id)
tomograms = list()

for r in dataset.runs:
    for s in r.tomogram_voxel_spacings:
        for t in s.tomograms:
            t.download_mrcfile(os.getcwd())
```

```
Traceback (most recent call last):

  File "Z:\mgflast\240911_Alg\full_dataset\download_from_czip.py", line 40, in <module>

    t.download_mrcfile(os.getcwd())

  File "C:\Users\mgflast\PycharmProjects\pommer\venv\lib\site-packages\cryoet_data_portal\_models.py", line 357, in download_mrcfile

    download_https(url, dest_path)

  File "C:\Users\mgflast\PycharmProjects\pommer\venv\lib\site-packages\cryoet_data_portal\_file_tools.py", line 46, in download_https

    total_size = int(fetch_request.headers["content-length"])

  File "C:\Users\mgflast\PycharmProjects\pommer\venv\lib\site-packages\requests\structures.py", line 52, in __getitem__

    return self._store[key.lower()][1]

KeyError: 'content-length'
```

So far it has occurred for the tomograms with these names:

29082023_NNPKrios_Arctis_Autotem_Position_113
29082023_NNPKrios_Arctis_Autotem_Position_115
29082023_NNPKrios_Arctis_Autotem_Position_116
29082023_NNPKrios_Arctis_Autotem_Position_117
29082023_NNPKrios_Arctis_Autotem_Position_118

Not so much of a problem for me but I thought I would report it.

Best,
Mart

**Comment by jgadling** [comment]
Sorry for the late reply - we were missing some data from this dataset so those `content-length` errors were essentially surfacing the fact that the tomogram files didn't exist in the portal. The missing data has been added to the portal, and this should work properly now!
