### ISSUE TITLE
Annotation dates are not serializable

### ISSUE THREAD

**Issue by kephale** [chanzuckerberg/cryoet-data-portal#21]
There are multiple `date` objects in `Annotation` objects in the data portal:
`'deposition_date': datetime.date(2023, 4, 1), 'release_date': datetime.date(2023, 6, 1), 'last_modified_date': datetime.date(2023, 6, 1)`. These objects are not serializable. I suggest converting these objects to iso 8601 strings before adding them to the data portal .

I ran into this trying to pretty print annotations, but this would affect other workflows that involve serializing annotations.

```
>>> json.dumps(annotations[0].to_dict(), indent=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kharrington/micromamba/envs/nesoi/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/kharrington/micromamba/envs/nesoi/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Users/kharrington/micromamba/envs/nesoi/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/kharrington/micromamba/envs/nesoi/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/kharrington/micromamba/envs/nesoi/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/kharrington/micromamba/envs/nesoi/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

**Comment by kephale** [comment]
Cool, this should be fine for me. I'll report back if I run into this again.
